### ISSUE TITLE
Navbar cutting off headers

### ISSUE THREAD

**Issue by sharlagelfand** [gadenbuie/boostrap-v3-theme-minty#1]
Any chance you know/understand what's causing the navbar to cutoff the header on the vignette pages, but not on the main/reference pages here?

https://sharlagelfand.github.io/opendatatoronto/index.html vs https://sharlagelfand.github.io/opendatatoronto/articles/opendatatoronto.html and https://sharlagelfand.github.io/opendatatoronto/articles/multifile_zip_resources.html

my limited css-fu is failing. thank you!

**Comment by gadenbuie** [comment]
It's a little issue with `pkgdown.css` interacting with the bootstrap theme.

pkgdown has a CSS rule like this

```css
.contents h1 {
  padding-top: 60px;
  margin-top: -40px;
}
```

This is a common pattern for taking into account the height of the navbar. But because I bumped up the size of the fonts a bit, the navbar is too tall.

I think this will work. Open up `pkgdown/extra.css` and add this on the last line

```css
.template-article .page-header h1 { padding-top: 120px; }
```

I used the `.template-article` class to avoid having this apply to the [reference page](https://sharlagelfand.github.io/opendatatoronto/reference/index.html) where things seem to be working fine.

**Comment by gadenbuie** [comment]
okay, just realized that's going to mess with the spacing of the first `h1` header on the front page... might have to think about this a bit more

**Comment by gadenbuie** [comment]
got it! This should be pretty robust now

```css
.template-article .contents > .page-header { margin-top: 50px; }
```

Turns out the front page uses the article template but has slightly different structure. This should apply the margin change but *only* on the regular article pages.
